#公共配置
server:
  port: 80
  tomcat:
    uri-encoding: utf-8
  servlet:
    contextpath: /my-film
#监控配置
management:
  port: 8090
  security:
    enabled: false

spring:
  #选择配置环境
  profiles:
    active: dev

  #邮件发送配置
  mail:
    host: smtp.qq.com
    username: 2637178586@qq.com
    password: fpzxwlqimtfbdjjj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  boot:
    admin:
      url: http://localhost:8000

#mybatis
mybatis-plus:
  # 实体类扫描
  type-aliases-package: com.paramount.entity
  # 配置映射文件位置
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      table-prefix: tb_
  configuration:
    # 开启驼峰匹配
    map-underscore-to-camel-case: true
    #缓存
    cache-enabled: false
    #事务超时时间
    default-statement-timeout: 1800
    #缓存 prepared statement 提高性能
    default-executor-type: reuse
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

---
#开发环境配置
server:
  port: 8090
spring:
  profiles: dev
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.111.64.94:3306/gj_movie?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true


#ES配置
gj_movie:
  elasticsearch:
    hostlist: ${eshostlist:47.111.64.94:9200} #多个结点中间用逗号分隔



